### ISSUE TITLE
Probe diode

### ISSUE THREAD

**Issue by YoungHillionaire** [MotorDynamicsLab/Nitehawk-SB#1]
Does it have bat diode connected to probe port?

**Comment by jwyse** [comment]
There is a Schottky diode (SS14) on probe pin 2: [schematic](https://github.com/MotorDynamicsLab/Nitehawk-SB/blob/master/Hardware/Nitehawk-SB%20V1.4%20Schematics.pdf).

**Comment by cneshi** [comment]
Yes there is a diode so the probe pin 2 is 24V tolerant
