### ISSUE TITLE
Can this board work with a 12v system ?

### ISSUE THREAD

**Issue by glennpierce** [MotorDynamicsLab/Nitehawk-SB#14]
Can this board work with a 12v system ?
The regulator seems to to accept a wide input range my over concern is the increased current . Can the USB cable cope ? 
Any other possible issues ?

**Comment by gyscos** [comment]
The doc mentions the USB cable is rated for 120w (at 24V), which would mean ~5A. If you're running 12V at 5A, the cable itself _should_ be fine. This _may_ be enough for a 40W hotend and a 1A extruder.

The electrical specifications for the board seem to indicate a min voltage of 20V though: https://docs.ldomotors.com/en/Toolboard/nitehawk-sb#electrical-specifications

**Comment by glennpierce** [comment]
Thanks. I think it possibly could if changing the resistors for the regulator but its probably not worth the hassle or risk.
