### ISSUE TITLE
gpio28/chamber thermistor shows wrong connector type

### ISSUE THREAD

**Issue by doomcrewinc** [MotorDynamicsLab/Nitehawk-SB#2]
In the images: 
/nhsb_pcb_pinout.png
/nhsb_pcb_pinout.svg
![Screenshot 2024-02-15 at 12 38 58](https://github.com/MotorDynamicsLab/Nitehawk-SB/assets/11277155/776e47a3-95d7-4667-be26-bea42d4be9d1)

The Chamber Thermistor / GPIO28 lists the connector type as "JST-XH2.5"

When I installed the board, I had to use a "JST-PH2" connector which was included in the kit.

This could cause confusion for people if they expect the Chamber Thermistor to directly plug in to the new Nitehawk board.

**Comment by cneshi** [comment]
Thank you for raising this issue, I have fixed it in this commit: 5c038ff8833832aaf801ac7cedaf7245eb51493e
