### ISSUE TITLE
GSTAT 00000001

### ISSUE THREAD

**Issue by aGAMEki** [MotorDynamicsLab/Nitehawk-SB#8]
Hello There, 

I Have a Problem für the Nitehawk and Galileo 2 Extruder. Since i have Built the Galileo 2 Extruder with the Nitehawk sometimes the Nitehawk shows the GSTAT Issue and the Print broke up.

"After I have rerouted all the cables, tightened all the screws, and checked all the connections, it ran for some time and then there were several failures during printing again. What could be the cause? Is the controller getting too hot in the Stealthburner? I don't have these problems with my Switchwire, only with my Voron 2.4."

**Comment by camerony** [comment]
Please ask in Discord, if you're still having problems.
